### ISSUE TITLE
Typo in Collections -> GroupBy exercise on play.kotlinlang.org

### ISSUE THREAD

**Issue by rusheb** [Kotlin/kotlin-koans-edu#11]
The [online tutorial](https://github.com/Kotlin/kotlin-koans-edu/blob/master/Collections/GroupBy/task.md) accesses `it.length()` as a method rather than a property (see screenshot) inside the `groupBy` statement: 

<img width="474" alt="image" src="https://user-images.githubusercontent.com/26048292/74184948-9f733680-4c3f-11ea-9a24-65bac3572280.png">

The code doesn't compile, and is inconsistent with the [snippet in this repo](https://github.com/Kotlin/kotlin-koans-edu/blob/master/Collections/GroupBy/task.md).

**Comment by timbodeit** [comment]
Relates to #13
