### ISSUE TITLE
"Max min" exercise instructions and solution use maxBy instead of maxByOrNull

### ISSUE THREAD

**Issue by ryanhaining** [Kotlin/kotlin-koans-edu#29]
In [Collections/Max min/task.md](https://github.com/Kotlin/kotlin-koans-edu/blob/master/Collections/Max%20min/task.md) and [Collections/Max min/src/Task.kt](https://github.com/Kotlin/kotlin-koans-edu/blob/master/Collections/Max%20min/src/Task.kt)

[maxBy is deprecated](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/max-by.html)

**Comment by danil-pavlov** [comment]
Thanks for the report! Fixed both at https://play.kotlinlang.org/koans/, and at the Edu plugin [marketplace](https://plugins.jetbrains.com/plugin/16628-kotlin-koans/versions/stable/140163)
