### ISSUE TITLE
Fold task solution is inefficient 

### ISSUE THREAD

**Issue by jjant** [Kotlin/kotlin-koans-edu#37]
One does not need to compute the union of all products ordered [(line 3)](https://github.com/Kotlin/kotlin-koans-edu/blob/master/Collections/Fold/src/Task.kt#L3) to start the fold, we can just take the first customer's items:
```kotlin
fun Shop.getProductsOrderedByAll(): Set<Product> {
    val firstCustomerProducts = customers[0].getOrderedProducts().toSet()
    return customers.fold(firstCustomerProducts) { orderedByAll, customer ->
        orderedByAll.intersect(customer.getOrderedProducts())
    }
}
```

This breaks if `customers` is empty, so we could also add a test case for that.

**Comment by danil-pavlov** [comment]
Thanks for your report. We decided to update this task in favor of the `reduce` implementation: #38
